// Iterative Fibonacci
fn fib2(n) {
  let a = 0;
  let b = 1;

  for i in 0..n {
    b = a + b;
    a = b - a;
  }

  return a;
};

let result2 = fib2(50);

println("Iterative Fibonacci: fib(50) = ", result2);

// This one is realllllllllllllyyyyyyyy inefficient, so dont run it with large values
fn fib(n) {
  if n <= 0 {
    return 0;
  }

  if n == 1 {
    return 1;
  }

  return fib(n - 1) + fib(n - 2);
};

let result = fib(25);

println("Recursive Fibonacci: fib(25) = ", result);

