let fib = fn(n) {
  if n == 0 {
    return 0;
  }

  if n == 1 {
    return 1;
  }

  return fib(n - 1) + fib(n - 2);
};

let result = fib(10);

print("Recursive Fibonacci: fib(10) = ", result);

// Iterative Fibonacci
let fib2 = fn(n) {
  let a = 0;
  let b = 1;

  for i in 0..n {
    b = a + b;
    a = b - a;
  }

  return a;
};

let result2 = fib2(10);

print("Iterative Fibonacci: fib(10) = ", result2);

[result, result2]
