let target = 500;

let is_prime = fn(n, primes) {
    for p in primes {
        if (n % p == 0) {
            return false;
        }
    }
    return true;
};

let summing_primes = fn(n) {
    if (n < 2) {
        return 0;
    }
    if (n == 2) {
        return 2;
    }
    let primes = [2];
    let sum = 2;
    for i in (3..=n) {
        if (is_prime(i, primes)) {
            sum = sum + i;

            push(primes, i);
        }
    }
    return sum;
};

print(summing_primes(target));

