name: Docs

on:
  push:
    branches:
      -  master

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Create rustdoc
        run: cargo doc

      # - name: Create CNAME
      #   run: |
      #     echo 'rustdoc.swc.rs' > target/doc/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: target/doc
          clean: true
          git-config-email: mail@pieterhuizenga.com
          repository-name: swc-project/rustdoc
          commit-message: "Update"
          single-commit: true
